name: Android Instrumentation

on:
  workflow_call:

jobs:
  instrumentation-tests:
    name: Instrumentation tests API 36
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 17
          cache: gradle

      - name: Enable KVM
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm

      - name: Run instrumentation tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 36
          target: google_apis
          arch: x86_64
          profile: pixel
          disable-animations: true
          emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          script: bash ./gradlew app:connectedHptoyDebugAndroidTest --no-daemon

      - name: Upload instrumentation test reports
        uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: hptoy-android-test-reports
          path: |
            app/build/outputs/androidTest-results/**
            app/build/reports/androidTests/**
